name: Intune Wipe

on:
  push:
    branches:
      - main # Adjust the branch name as needed

jobs:
  intune_wipe_job:
    runs-on: ubuntu-latest # You can choose other platforms like windows-latest or macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Replace 'x' with your desired Python version

      - name: Set up secrets
        env:
          INTUNE_USERNAME_SECRET: ${{ secrets.INTUNE_USERNAME }} # Replace with the actual secret name
          INTUNE_PASSWORD_SECRET: ${{ secrets.INTUNE_PASSWORD }} # Replace with the actual secret name
        run: |
          # Download the Python script
          curl -o intune_wipe.py https://raw.githubusercontent.com/your-repo/intune_wipe.py

      - name: Run Intune Wipe
        run: python intune_wipe.py
